### ISSUE TITLE
Выделить код создания документа в отдельную функцию

### ISSUE THREAD

**Issue by DennisMorosoff** [EvgenyKuksov/Kuksov-Laba-1#2]
Входной параметр функции: массив строк
Выходной параметр функции: WordDocument

Внутри Button1Click только подготовка массива строк и необходимые проверки (например, на пустоту)

**Comment by EvgenyKuksov** [comment]
Денис Иванович, у меня не работает конструкция "ifthen", не могу понять почему.
Так же я проверку на пустоту Эдитов написал, но из-за нее при компиляции вылетает ошибка "Invalid class typecast"
